import "./globals.css";
import { CartProvider } from '@/context/cartProvider'
import Navbar from '../components/navbar'
import Footer from "@/components/footer";



export const metadata = {
  title: "Next js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <CartProvider>
          <Navbar />
          <main className="flex-1">{children}</main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}

