import "./globals.css";
import {CartProvider} from '@/context/cartProvider'
import Navbar from '../components/navbar'



export const metadata = {
  title: "Next js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body>
      <CartProvider>
        <Navbar />
        {children}
        </CartProvider>
        </body>

      
    </html>
  );
}

